version: 2.1
jobs:
  build:
    docker:
    - image: circleci/openjdk:11-jdk
    steps:
    - checkout
    - run:
        name: Analyze on SonarCloud
        command: gradle build sonarqube -Dsonar.projectKey="algorithmikk_jukebox-settings-control" -Dsonar.organization="algorithmikk" -Dsonar.host.url="https://sonarcloud.io"
    - store_artifacts:
        path:  ${buildDir}/jacoco

workflows:
  main:
    jobs:
    - build:
        context: SonarCloud